spring:
  application:
    name: springboot2-essentials
  datasource:
    url: jdbc:mysql://db:3306/db?useSSL=false&createDatabaseIfNotExist=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect